services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak-tutorial
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://pgdb:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_LOG_LEVEL: debug
    command: ["start-dev"]
  pgdb:
    build:
      context: .
      dockerfile: Dockerfile-pgsql
    container_name: pgdb-kc-tutorial
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: example
